<div class="col-md-12 form-login-register">
	<h1 class="page-title">Seja bem vindo!</h1>
	<div class="col-md-6 form-login">
		<h2>Faça seu login</h2>
		<form method="POST" action="login/post">
			<div class="form-group">
			    <label for="email">Email address</label>
			    <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail">
			</div>
			<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha">
			</div>
			<button type="submit" class="btn btn-default">Entrar</button>
		</form>
	</div>
	<div class="col-md-6 form-register">
		<h2>Registre-se</h2>
		<form method="POST" action="register/post">
			<div class="form-group">
			    <label for="name">Name</label>
			    <input type="name" name="name" class="form-control" id="name" placeholder="Digite seu nome">
			</div>
			<div class="form-group">
			    <label for="email">Email address</label>
			    <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail">
			</div>
			<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha">
			</div>
			<div class="form-group">
			    <label for="confirmpassword">Confirm Password</label>
			    <input type="password" name="confirmpassword" class="form-control" id="confirmpassword" placeholder="Confirme sua senha">
			</div>
			<button type="submit" class="btn btn-default">Registrar</button>
		</form>
	</div>
</div>
