<div class="col-md-12">
	<h1>Login/Register</h1>
	<div class="col-md-6">
		<h2>Register</h2>
		<form method="POST" action="login">
			<div class="form-group">
			    <label for="email">Email address</label>
			    <input type="email" name="email" class="form-control" id="email" placeholder="Email">
			</div>
			<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>
	<div class="col-md-6">
		<h2>Register</h2>
		<form method="POST" action="register">
			<div class="form-group">
			    <label for="name">Name</label>
			    <input type="name" name="name" class="form-control" id="name" placeholder="Name">
			</div>
			<div class="form-group">
			    <label for="email">Email address</label>
			    <input type="email" name="email" class="form-control" id="email" placeholder="Email">
			</div>
			<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
			</div>
			<div class="form-group">
			    <label for="confirmpassword">Confirm Password</label>
			    <input type="password" name="confirmpassword" class="form-control" id="confirmpassword" placeholder="Confirm Password">
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>
</div>
